server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/ilisten
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

